apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MERN-blog
  annotations:
    github.com/project-slug: pankaj139/MERN-blog
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  type: blog
  lifecycle: experimental
  owner: observability
  providesApis: [MERN-Blog-api]
  system: examples
  description: |
    A MERN stack blog application
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: MERN-Blog-api
  description: ALL api related to MERN Blog
spec:
  type: openapi
  lifecycle: production
  owner: observability
  system: example
  definition: |
    $yaml: api.yaml
