apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MERN-blog
  annotations:
    github.com/project-slug: pankaj139/MERN-blog
spec:
  type: other
  lifecycle: unknown
  owner: observability
